datasource:
  sampleapp:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect